# Site settings
title: Dan the Developer
header-img: img/home-bg.png
email: d.schoch90@gmail.com
copyright_name: danschoch
description: > # this means to ignore newlines until "baseurl:"
  A Non-Tech Guy's Journey Into Tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  danschoch
learn_profile: danschoch
email_username: d.schoch90@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
